export const DEFAULT_SITE_SETTINGS = {
  colors: {
    forest: "#072f1b",
    forest2: "#0c4728",
    leaf: "#4cc46f",
    lime: "#b6e650",
    cream: "#f4f2e9",
    ink: "#122019",
  },
  tickerText: "اپنی مدد آپ، اجتماعی تعاون اور خدمتِ خلق | صاف گاؤں، سرسبز گاؤں، مثالی گاؤں — ہماری مشترکہ پہچان۔ 🌱",
  introTitle: "کلین اینڈ گرین سنگراں",
  introSubtitle: "ایک مشن، ایک عہد، ایک مثالی گاؤں",
  introSummary: "ہم سب اہلیانِ سنگراں کا مشترکہ عزم ہے کہ صفائی، شجرکاری، خوبصورتی، نظم و ضبط اور باہمی تعاون کے ذریعے اپنے گاؤں کو علاقے کا سب سے منفرد، سرسبز اور مثالی گاؤں بنائیں۔",
  ongoingProjectEn: "Cemetery Care & Plantation",
  ongoingProjectUr: "قبرستان کی بہتری اور شجرکاری",
  ongoingProjectDateEn: "Work currently in progress",
  ongoingProjectDateUr: "کام جاری ہے",
  comingProjectEn: "Clean Water & Green Zone",
  comingProjectUr: "صاف پانی اور گرین زون منصوبہ",
  comingProjectDateEn: "Expected soon",
  comingProjectDateUr: "جلد شروع ہوگا",
  socialLinks: [],
  paymentMethods: [],
  projectFaithSlides: [
    {
      id: "faith-1",
      typeEn: "Quranic guidance",
      typeUr: "قرآنی رہنمائی",
      arabic: "وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ",
      translationUr: "نیکی اور تقویٰ کے کاموں میں ایک دوسرے کی مدد کرو۔",
      translationEn: "Cooperate with one another in goodness and righteousness.",
      reference: "Surah Al-Ma'idah 5:2",
      enabled: true,
    },
    {
      id: "faith-2",
      typeEn: "Quranic reminder",
      typeUr: "قرآنی پیغام",
      arabic: "إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ",
      translationUr: "بے شک اللہ نیکی کرنے والوں سے محبت کرتا ہے۔",
      translationEn: "Indeed, Allah loves those who do good.",
      reference: "Surah Al-Baqarah 2:195",
      enabled: true,
    },
    {
      id: "faith-3",
      typeEn: "Hadith",
      typeUr: "حدیثِ مبارک",
      arabic: "مَنْ كَانَ فِي حَاجَةِ أَخِيهِ كَانَ اللَّهُ فِي حَاجَتِهِ",
      translationUr: "جو شخص اپنے بھائی کی حاجت پوری کرنے میں لگا رہتا ہے، اللہ اس کی حاجت پوری فرماتا ہے۔",
      translationEn: "Whoever fulfills the needs of his brother, Allah will fulfill his needs.",
      reference: "Sahih al-Bukhari 2442",
      enabled: true,
    },
  ],
};

export function mergeSiteSettings(value = {}) {
  return {
    ...DEFAULT_SITE_SETTINGS,
    ...value,
    colors: {
      ...DEFAULT_SITE_SETTINGS.colors,
      ...(value.colors || {}),
    },
    socialLinks: Array.isArray(value.socialLinks) ? value.socialLinks : DEFAULT_SITE_SETTINGS.socialLinks,
    paymentMethods: Array.isArray(value.paymentMethods) ? value.paymentMethods : DEFAULT_SITE_SETTINGS.paymentMethods,
    projectFaithSlides: Array.isArray(value.projectFaithSlides) ? value.projectFaithSlides : DEFAULT_SITE_SETTINGS.projectFaithSlides,
  };
}
